include: package:lints/recommended.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "example/brew_catalog/**"
  errors:
    invalid_annotation_target: ignore
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    - always_declare_return_types
    - annotate_overrides
    - avoid_empty_else
    - avoid_relative_lib_imports
    - cancel_subscriptions
    - close_sinks
    - combinators_ordering
    - directives_ordering
    - no_adjacent_strings_in_list
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_fields
    - prefer_final_locals
    - prefer_single_quotes
    - sort_pub_dependencies
    - unawaited_futures
    - unnecessary_lambdas
    - unnecessary_parenthesis
    - unreachable_from_main
